args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) stop('usage: Rscript data-raw/probe_object.R <package> <object>')
pkg <- args[[1]]; obj <- paste(args[-1], collapse = ' ')
if (!requireNamespace(pkg, quietly = TRUE)) stop('Package not installed: ', pkg)
e <- new.env(parent = emptyenv())
suppressWarnings(utils::data(list = obj, package = pkg, envir = e))
if (!exists(obj, envir = e, inherits = FALSE)) stop('Object not found: ', pkg, '::', obj)
x <- get(obj, envir = e, inherits = FALSE)
str(x)
