#' Automated Report Generation for Network Meta-Analysis
#'
#' Generate publication-ready Word, PDF, and HTML reports from NMA results.
#' Includes all tables, figures, and narrative text following best practices.
#'
#' @name automated_reporting
NULL

#' Generate Complete NMA Report
#'
#' Create a comprehensive report including all analysis results, tables,
#' figures, and interpretations in Word, PDF, or HTML format.
#'
#' @param nma_results Comprehensive NMA results (from run_comprehensive_nma)
#' @param output_file Output file path (extension determines format)
#' @param format Output format: "word", "pdf", "html", or "auto" (from extension)
#' @param title Report title
#' @param author Report author(s)
#' @param include_methods Include methods section
#' @param include_code Include R code appendix
#' @param template Report template: "standard", "brief", "detailed"
#' @return Path to generated report
#' @export
#' @examples
#' \dontrun{
#' results <- run_comprehensive_nma(data, sm = "OR")
#'
#' # Generate Word report
#' generate_nma_report(results, "nma_report.docx")
#'
#' # Generate PDF report
#' generate_nma_report(results, "nma_report.pdf", template = "detailed")
#'
#' # Generate HTML report
#' generate_nma_report(results, "nma_report.html")
#' }
generate_nma_report <- function(nma_results,
                                output_file,
                                format = c("auto", "word", "pdf", "html"),
                                title = "Network Meta-Analysis Report",
                                author = "Generated by powerNMA",
                                include_methods = TRUE,
                                include_code = FALSE,
                                template = c("standard", "brief", "detailed")) {

  format <- match.arg(format)
  template <- match.arg(template)

  # Auto-detect format from file extension
  if (format == "auto") {
    ext <- tools::file_ext(output_file)
    format <- switch(ext,
                    "docx" = "word",
                    "pdf" = "pdf",
                    "html" = "html",
                    stop("Cannot determine format from extension. Use .docx, .pdf, or .html"))
  }

  # Check if rmarkdown is available
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' required for report generation. Install with: install.packages('rmarkdown')")
  }

  # Create temporary R Markdown file
  rmd_content <- create_rmd_content(
    nma_results = nma_results,
    title = title,
    author = author,
    format = format,
    include_methods = include_methods,
    include_code = include_code,
    template = template
  )

  # Write to temporary file
  temp_rmd <- tempfile(fileext = ".Rmd")
  writeLines(rmd_content, temp_rmd)

  # Render report
  message(sprintf("Generating %s report...", format))

  tryCatch({
    rmarkdown::render(
      input = temp_rmd,
      output_file = basename(output_file),
      output_dir = dirname(output_file),
      output_format = get_output_format(format),
      quiet = FALSE
    )

    message(sprintf("✓ Report generated: %s", output_file))
    output_file

  }, error = function(e) {
    warning(sprintf("Report generation failed: %s", e$message))
    warning("Falling back to text report...")

    # Fallback to simple text report
    generate_text_report(nma_results, output_file)
  })
}

#' Create R Markdown Content
#'
#' @param nma_results NMA results object
#' @param title Report title
#' @param author Author name
#' @param format Output format
#' @param include_methods Include methods section
#' @param include_code Include code
#' @param template Template type
#' @return Character vector with RMarkdown content
#' @keywords internal
create_rmd_content <- function(nma_results, title, author, format,
                               include_methods, include_code, template) {

  # YAML header
  yaml <- create_yaml_header(title, author, format)

  # Main content sections
  sections <- list(
    create_executive_summary(nma_results),
    create_introduction_section(),
    if (include_methods) create_methods_section() else NULL,
    create_results_section(nma_results, template),
    create_discussion_section(nma_results),
    create_conclusions_section(nma_results),
    create_tables_section(nma_results),
    create_figures_section(nma_results),
    if (include_code) create_code_appendix(nma_results) else NULL
  )

  # Combine all sections
  c(yaml, unlist(sections))
}

#' Create YAML Header
#'
#' @keywords internal
create_yaml_header <- function(title, author, format) {

  output_format <- switch(format,
    "word" = "word_document",
    "pdf" = "pdf_document",
    "html" = "html_document"
  )

  c(
    "---",
    sprintf("title: \"%s\"", title),
    sprintf("author: \"%s\"", author),
    sprintf("date: \"%s\"", Sys.Date()),
    sprintf("output: %s", output_format),
    "---",
    "",
    ""
  )
}

#' Create Executive Summary
#'
#' @keywords internal
create_executive_summary <- function(nma_results) {

  n_treatments <- if (!is.null(nma_results$network_geometry)) {
    nma_results$network_geometry$n_treatments
  } else {
    length(unique(c(nma_results$data$treat1, nma_results$data$treat2)))
  }

  n_studies <- if (!is.null(nma_results$network_geometry)) {
    nma_results$network_geometry$n_studies
  } else {
    length(unique(nma_results$data$studlab))
  }

  best_treatment <- if (!is.null(nma_results$rankings)) {
    nma_results$rankings$summary$Treatment[1]
  } else {
    "Not assessed"
  }

  c(
    "# Executive Summary",
    "",
    sprintf("This network meta-analysis compared **%d treatments** across **%d studies**.",
           n_treatments, n_studies),
    "",
    "## Key Findings",
    "",
    sprintf("- **Best treatment**: %s", best_treatment),
    "",
    if (!is.null(nma_results$heterogeneity)) {
      sprintf("- **Heterogeneity**: I² = %.1f%% (%s)",
             nma_results$heterogeneity$I2_percent,
             gsub("\\(.*", "", nma_results$heterogeneity$i2_interpretation))
    } else "",
    "",
    if (!is.null(nma_results$node_splitting) && nma_results$node_splitting$n_inconsistent > 0) {
      sprintf("- **⚠ Inconsistency detected** in %d of %d comparisons",
             nma_results$node_splitting$n_inconsistent,
             nma_results$node_splitting$n_tests)
    } else "- **✓ No significant inconsistency detected**",
    "",
    if (!is.null(nma_results$pub_bias) && !is.null(nma_results$pub_bias$summary)) {
      n_sig <- sum(nma_results$pub_bias$summary$Significant, na.rm = TRUE)
      if (n_sig > 0) {
        sprintf("- **⚠ Potential publication bias** (%d of %d tests significant)",
               n_sig, nrow(nma_results$pub_bias$summary))
      } else {
        "- **✓ No evidence of publication bias**"
      }
    } else "",
    "",
    "---",
    ""
  )
}

#' Create Introduction Section
#'
#' @keywords internal
create_introduction_section <- function() {
  c(
    "# Introduction",
    "",
    "Network meta-analysis (NMA) extends pairwise meta-analysis by incorporating ",
    "direct and indirect evidence from multiple treatments simultaneously. This allows ",
    "comparison of treatments that have not been directly compared in head-to-head trials.",
    "",
    "This report presents a comprehensive NMA following current best practice guidelines ",
    "from Cochrane, JAMA, and BMJ. All analyses were conducted using the powerNMA package ",
    "in R, which implements state-of-the-art statistical methods.",
    "",
    "---",
    ""
  )
}

#' Create Methods Section
#'
#' @keywords internal
create_methods_section <- function() {
  c(
    "# Methods",
    "",
    "## Data Sources and Study Selection",
    "",
    "Studies were identified through systematic literature search following PRISMA guidelines. ",
    "Pairwise data were extracted including treatment effects, standard errors, and study characteristics.",
    "",
    "## Statistical Analysis",
    "",
    "### Core Network Meta-Analysis",
    "",
    "We conducted frequentist network meta-analysis using a random-effects model, ",
    "which accounts for between-study heterogeneity. Treatment effects were synthesized ",
    "using the netmeta package in R.",
    "",
    "### Treatment Rankings",
    "",
    "Treatments were ranked using Surface Under the Cumulative Ranking (SUCRA) scores, ",
    "which quantify the probability of each treatment being among the best options. ",
    "SUCRA scores range from 0% (certainly worst) to 100% (certainly best).",
    "",
    "### Assessment of Heterogeneity",
    "",
    "Between-study heterogeneity was quantified using I² and τ² statistics. ",
    "Prediction intervals were calculated to indicate the range of expected effects ",
    "in future similar studies.",
    "",
    "### Assessment of Inconsistency",
    "",
    "Network inconsistency (disagreement between direct and indirect evidence) was assessed using:",
    "",
    "- **Node-splitting**: Comparing direct vs indirect evidence for each comparison",
    "- **Design-by-treatment interaction**: Decomposing heterogeneity",
    "- **Loop inconsistency**: Testing closed triangular loops",
    "",
    "### Publication Bias Assessment",
    "",
    "Small-study effects and publication bias were evaluated using comparison-adjusted ",
    "funnel plots and statistical tests (Egger's and Begg's tests).",
    "",
    "## Software",
    "",
    "All analyses were conducted in R (version 4.x) using:",
    "",
    "- `powerNMA`: Comprehensive NMA analysis",
    "- `netmeta`: Core NMA functions",
    "- `meta`: Meta-analysis methods",
    "",
    "---",
    ""
  )
}

#' Create Results Section
#'
#' @keywords internal
create_results_section <- function(nma_results, template) {

  sections <- list(
    c(
      "# Results",
      "",
      "## Network Characteristics",
      ""
    )
  )

  if (!is.null(nma_results$network_geometry)) {
    geom <- nma_results$network_geometry
    sections <- c(sections, list(c(
      sprintf("The evidence network included **%d studies** comparing **%d treatments** ",
             geom$n_studies, geom$n_treatments),
      sprintf("through **%d pairwise comparisons**. The network density was %.2f, ",
             geom$n_comparisons, geom$density),
      "indicating a well-connected network.",
      "",
      sprintf("- Studies: %d", geom$n_studies),
      sprintf("- Treatments: %d", geom$n_treatments),
      sprintf("- Comparisons: %d", geom$n_comparisons),
      sprintf("- Density: %.2f", geom$density),
      sprintf("- Mean degree: %.1f", geom$mean_degree),
      ""
    )))
  }

  # Treatment Rankings
  if (!is.null(nma_results$rankings)) {
    sections <- c(sections, list(c(
      "## Treatment Rankings",
      "",
      "Based on SUCRA scores, the top 5 treatments were:",
      ""
    )))

    top5 <- head(nma_results$rankings$summary, 5)
    for (i in 1:nrow(top5)) {
      sections <- c(sections, list(
        sprintf("%d. **%s**: SUCRA = %.1f%%, P(best) = %.1f%%",
               i, top5$Treatment[i], top5$SUCRA[i], top5$ProbBest[i])
      ))
    }
    sections <- c(sections, list(""))
  }

  # Heterogeneity
  if (!is.null(nma_results$heterogeneity)) {
    het <- nma_results$heterogeneity
    sections <- c(sections, list(c(
      "## Heterogeneity",
      "",
      sprintf("Between-study heterogeneity was %s (I² = %.1f%%, τ = %.3f). ",
             tolower(het$i2_interpretation), het$I2_percent, het$tau),
      "",
      sprintf("- I² = %.1f%%", het$I2_percent),
      sprintf("- τ = %.3f", het$tau),
      sprintf("- Q statistic: %.2f (df = %d, p = %.4f)",
             het$Q_statistic, het$Q_df, het$Q_pvalue),
      ""
    )))
  }

  # Inconsistency
  if (!is.null(nma_results$node_splitting)) {
    ns <- nma_results$node_splitting
    sections <- c(sections, list(c(
      "## Network Inconsistency",
      "",
      sprintf("Node-splitting analysis tested %d comparisons for inconsistency. ",
             ns$n_tests),
      sprintf("**%d comparisons** showed significant disagreement between direct and indirect evidence (p < 0.10).",
             ns$n_inconsistent),
      ""
    )))
  }

  # Publication Bias
  if (!is.null(nma_results$pub_bias)) {
    sections <- c(sections, list(c(
      "## Publication Bias",
      "",
      "Multiple statistical tests were conducted to assess potential publication bias:",
      ""
    )))

    if (!is.null(nma_results$pub_bias$summary) && nrow(nma_results$pub_bias$summary) > 0) {
      n_sig <- sum(nma_results$pub_bias$summary$Significant, na.rm = TRUE)
      sections <- c(sections, list(
        sprintf("- **%d of %d tests** suggested potential bias", n_sig, nrow(nma_results$pub_bias$summary))
      ))
    }

    sections <- c(sections, list(""))
  }

  c(unlist(sections), "---", "")
}

#' Create Discussion Section
#'
#' @keywords internal
create_discussion_section <- function(nma_results) {

  has_issues <- FALSE

  if (!is.null(nma_results$node_splitting) && nma_results$node_splitting$n_inconsistent > 0) {
    has_issues <- TRUE
  }

  if (!is.null(nma_results$pub_bias) && !is.null(nma_results$pub_bias$summary)) {
    if (sum(nma_results$pub_bias$summary$Significant, na.rm = TRUE) > 0) {
      has_issues <- TRUE
    }
  }

  c(
    "# Discussion",
    "",
    "## Summary of Findings",
    "",
    "This network meta-analysis provides a comprehensive comparison of available treatments. ",
    "The evidence network was well-connected, allowing both direct and indirect comparisons.",
    "",
    if (!is.null(nma_results$rankings)) {
      sprintf("Treatment rankings suggest that **%s** may be the most effective option, ",
             nma_results$rankings$summary$Treatment[1])
    } else "",
    "though clinical decision-making should consider additional factors including ",
    "safety, cost, patient preferences, and clinical context.",
    "",
    "## Limitations",
    "",
    if (has_issues) {
      c(
        "Several limitations should be noted:",
        "",
        if (!is.null(nma_results$node_splitting) && nma_results$node_splitting$n_inconsistent > 0) {
          "- **Inconsistency detected**: Some comparisons showed disagreement between direct and indirect evidence"
        } else NULL,
        "",
        if (!is.null(nma_results$pub_bias$summary) && sum(nma_results$pub_bias$summary$Significant) > 0) {
          "- **Potential publication bias**: Statistical tests suggest possible small-study effects"
        } else NULL,
        ""
      )
    } else {
      c(
        "The analysis showed no major methodological concerns:",
        "",
        "- Network consistency was maintained",
        "- No evidence of publication bias",
        ""
      )
    },
    "## Clinical Implications",
    "",
    "These findings can inform clinical guidelines and treatment decisions. However, ",
    "results should be interpreted in the context of individual patient characteristics ",
    "and local healthcare settings.",
    "",
    "---",
    ""
  )
}

#' Create Conclusions Section
#'
#' @keywords internal
create_conclusions_section <- function(nma_results) {

  best_treatment <- if (!is.null(nma_results$rankings)) {
    nma_results$rankings$summary$Treatment[1]
  } else {
    "[Best treatment not determined]"
  }

  c(
    "# Conclusions",
    "",
    sprintf("This comprehensive network meta-analysis suggests that **%s** ",
           best_treatment),
    "may be among the most effective treatments based on available evidence. ",
    "",
    "Future research should:",
    "",
    "- Conduct head-to-head trials for key comparisons lacking direct evidence",
    "- Investigate sources of heterogeneity through additional meta-regression",
    "- Assess long-term outcomes and safety profiles",
    "",
    "---",
    ""
  )
}

#' Create Tables Section
#'
#' @keywords internal
create_tables_section <- function(nma_results) {
  c(
    "# Tables",
    "",
    "## Table 1: Treatment Rankings (SUCRA Scores)",
    "",
    if (!is.null(nma_results$rankings)) {
      c(
        "```{r echo=FALSE}",
        "knitr::kable(nma_results$rankings$summary, digits = 1)",
        "```",
        ""
      )
    } else {
      "Rankings not available.",
      ""
    },
    "---",
    ""
  )
}

#' Create Figures Section
#'
#' @keywords internal
create_figures_section <- function(nma_results) {
  c(
    "# Figures",
    "",
    "## Figure 1: Network Diagram",
    "",
    "*Network diagram showing connections between treatments*",
    "",
    "## Figure 2: Forest Plot",
    "",
    "*Forest plot of treatment effects vs reference*",
    "",
    "## Figure 3: Rank-o-gram",
    "",
    "*Probability of each treatment at each rank position*",
    "",
    "---",
    ""
  )
}

#' Create Code Appendix
#'
#' @keywords internal
create_code_appendix <- function(nma_results) {
  c(
    "# Appendix: R Code",
    "",
    "## Data Preparation and Analysis",
    "",
    "```{r eval=FALSE}",
    "# Load package",
    "library(powerNMA)",
    "",
    "# Run comprehensive NMA",
    "results <- run_comprehensive_nma(",
    "  data = your_data,",
    "  sm = 'OR',",
    "  assess_inconsistency = TRUE,",
    "  assess_publication_bias = TRUE,",
    "  generate_plots = TRUE",
    ")",
    "```",
    ""
  )
}

#' Get Output Format for R Markdown
#'
#' @keywords internal
get_output_format <- function(format) {
  switch(format,
    "word" = "word_document",
    "pdf" = "pdf_document",
    "html" = "html_document"
  )
}

#' Generate Simple Text Report
#'
#' Fallback for when R Markdown fails
#'
#' @keywords internal
generate_text_report <- function(nma_results, output_file) {

  # Change extension to .txt
  output_file <- sub("\\.[^.]+$", ".txt", output_file)

  text_content <- c(
    "═══════════════════════════════════════════════════════════",
    "  NETWORK META-ANALYSIS REPORT",
    "═══════════════════════════════════════════════════════════",
    "",
    sprintf("Generated: %s", Sys.time()),
    "",
    "EXECUTIVE SUMMARY",
    "─────────────────────────────────────────────────────────",
    ""
  )

  if (!is.null(nma_results$rankings)) {
    text_content <- c(text_content,
      "Top 5 Treatments (by SUCRA):",
      ""
    )

    top5 <- head(nma_results$rankings$summary, 5)
    for (i in 1:nrow(top5)) {
      text_content <- c(text_content,
        sprintf("  %d. %s - SUCRA: %.1f%%, P(best): %.1f%%",
               i, top5$Treatment[i], top5$SUCRA[i], top5$ProbBest[i])
      )
    }
  }

  writeLines(text_content, output_file)
  message(sprintf("Text report generated: %s", output_file))

  output_file
}

#' Create Quick Summary Report
#'
#' Generate a one-page summary of NMA results
#'
#' @param nma_results Comprehensive NMA results
#' @param output_file Output file path
#' @return Path to generated file
#' @export
#' @examples
#' \dontrun{
#' results <- run_comprehensive_nma(data)
#' quick_summary_report(results, "summary.txt")
#' }
quick_summary_report <- function(nma_results, output_file) {

  content <- c(
    "═══════════════════════════════════════════════════════════",
    "  NMA QUICK SUMMARY",
    "═══════════════════════════════════════════════════════════",
    "",
    sprintf("Date: %s", Sys.Date()),
    ""
  )

  # Network info
  if (!is.null(nma_results$network_geometry)) {
    geom <- nma_results$network_geometry
    content <- c(content,
      "NETWORK:",
      sprintf("  Studies: %d", geom$n_studies),
      sprintf("  Treatments: %d", geom$n_treatments),
      sprintf("  Comparisons: %d", geom$n_comparisons),
      ""
    )
  }

  # Rankings
  if (!is.null(nma_results$rankings)) {
    content <- c(content,
      "TOP 3 TREATMENTS:",
      ""
    )

    top3 <- head(nma_results$rankings$summary, 3)
    for (i in 1:nrow(top3)) {
      content <- c(content,
        sprintf("  %d. %s (SUCRA: %.1f%%)", i, top3$Treatment[i], top3$SUCRA[i])
      )
    }
    content <- c(content, "")
  }

  # Quality indicators
  content <- c(content, "QUALITY INDICATORS:", "")

  if (!is.null(nma_results$heterogeneity)) {
    content <- c(content,
      sprintf("  Heterogeneity: I² = %.1f%%", nma_results$heterogeneity$I2_percent)
    )
  }

  if (!is.null(nma_results$node_splitting)) {
    content <- c(content,
      sprintf("  Inconsistency: %d/%d comparisons",
             nma_results$node_splitting$n_inconsistent,
             nma_results$node_splitting$n_tests)
    )
  }

  content <- c(content,
    "",
    "═══════════════════════════════════════════════════════════"
  )

  writeLines(content, output_file)
  message(sprintf("Quick summary saved: %s", output_file))

  output_file
}
